### ISSUE TITLE
Kube-prometheus - After enabling webhook and authentication i can't get logs from my pods with kubectl

### ISSUE THREAD

**Issue by Zwordi** [coreos/prometheus-operator#1503]
**What did you do?**
I just finished my setup by enabling : 

> 
>     --authentication-token-webhook=true This flag enables, that a ServiceAccount token can be used to authenticate against the kubelet(s).
>     --authorization-mode=Webhook This flag enables, that the kubelet will perform an RBAC request with the API to determine, whether the requesting entity (Prometheus in this case) is allow to access a resource, in specific for this project the /metrics endpoint.

**What did you expect to see?**
 
I have my grafana working fine with all the default dashboard.

**What did you see instead? Under which circumstances?**

When i'm using the dashboard or kubectl i get : 
` Forbidden (user=system:node:kubYY, verb=get, resource=nodes, subresource=proxy) ( pods/log XXX) `

**Environment**

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5+coreos.0", GitCommit:"0d082e389e1f4311dc5d225eb77f9688c50d340a", GitTreeState:"clean", BuildDate:"2018-03-21T21:10:44Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	kubespray - vms under kvm.

* Manifests:

```
none
```

* Prometheus Operator Logs:

```
 kubX01 kubelet[12646]: I0619 11:06:11.262096   12646 server.go:248] Forbidden (user=system:node:kubX03, verb=get, resource=nodes, subresource=proxy)
 kubX01 kubelet[12646]: I0619 11:06:11.294486   12646 server.go:796] GET /containerLogs/toto/XXX-YYYY-4dl45/XXX-YYYY-XXX?tailLines=5000&timestamps=true: (43.821124ms) 403
 kubX01 kubelet[12646]: goroutine 23187 [running]:
 kubX01 kubelet[12646]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc421bf0620, 0x193)
 kubX01 kubelet[12646]: #011/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:207 +0xdd
 kubX01 kubelet[12646]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc421bf0620, 0x193)
 kubX01 kubelet[12646]: #011/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:186 +0x35
 kubX01 kubelet[12646]: k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Response).WriteHeader(0xc424480720, 0x193)
 kubX01 kubelet[12646]: #011/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/response.go:201 +0x41
 kubX01 kubelet[12646]: k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Response).WriteErrorString(0xc424480720, 0x193, 0xc4228a82d0, 0x50, 0x4, 0xc4228a82d0)
 kubX01 kubelet[12646]: #011/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/response.go:181 +0x46
 kubX01 kubelet[12646]: k8s.io/kubernetes/pkg/kubelet/server.(*Server).InstallAuthFilter.func1(0xc424046d80, 0xc424480720, 0xc424046e10)
 kubX01 kubelet[12646]: #011/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/server.go:249 +0x4b5
 kubX01 kubelet[12646]: k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc424046e10, 0xc424046d80, 0xc424480720)
 kubX01 kubelet[12646]: #011/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/filter.go:19 +0x68
 kubX01 kubelet[12646]: k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc4202454d0, 0xa6fda80, 0xc421bf0620, 0xc421288c00)
 kubX01 kubelet[12646]: #011/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:274 +0x8ff
 kubX01 kubelet[12646]: k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).(k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.dispatch)-fm(0xa6fda80, 0xc421bf0620, 0xc421288c00)
 kubX01 kubelet[12646]: #011/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:120 +0x48
 kubX01 kubelet[12646]: net/http.HandlerFunc.ServeHTTP(0xc420398520, 0xa6fda80, 0xc421bf0620, 0xc421288c00)
 kubX01 kubelet[12646]: #011/usr/local/go/src/net/http/server.go:1918 +0x44
 kubX01 kubelet[12646]: net/http.(*ServeMux).ServeHTTP(0xc420f4d440, 0xa6fda80, 0xc421bf0620, 0xc421288c00)
 kubX01 kubelet[12646]: #011/usr/local/go/src/net/http/server.go:2254 +0x130
 kubX01 kubelet[12646]: k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).ServeHTTP(0xc4202454d0, 0xa6fda80, 0xc421bf0620, 0xc421288c00)
 kubX01 kubelet[12646]: #011/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:292 +0x4d
 kubX01 kubelet[12646]: k8s.io/kubernetes/pkg/kubelet/server.(*Server).ServeHTTP(0xc42101dd60, 0xa6fda80, 0xc421bf0620, 0xc421288c00)
 kubX01 kubelet[12646]: #011/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/server.go:795 +0x106
 kubX01 kubelet[12646]: net/http.serverHandler.ServeHTTP(0xc4213fcf70, 0xa6fef80, 0xc421df1b20, 0xc421288c00)
 kubX01 kubelet[12646]: #011/usr/local/go/src/net/http/server.go:2619 +0xb4
 kubX01 kubelet[12646]: net/http.(*conn).serve(0xc4239cff40, 0xa7027c0, 0xc422a24c80)
 kubX01 kubelet[12646]: #011/usr/local/go/src/net/http/server.go:1801 +0x71d
 kubX01 kubelet[12646]: created by net/http.(*Server).Serve
 kubX01 kubelet[12646]: #011/usr/local/go/src/net/http/server.go:2720 +0x288
 kubX01 kubelet[12646]: logging error output: "Forbidden (user=system:node:kubX03, verb=get, resource=nodes, subresource=proxy)"
 kubX01 kubelet[12646]:  [[Go-http-client/1.1] CCC.CCC.CCC.CCC:44320]
```

Based on the documentation of [kubernetes](https://kubernetes.io/docs/admin/kubelet-authentication-authorization/#kubelet-authentication) i need : 

To subdivide access to the kubelet API, delegate authorization to the API server:

-     ensure the authorization.k8s.io/v1beta1 API group is enabled in the API server
-     start the kubelet with the --authorization-mode=Webhook and the --kubeconfig flags
-     the kubelet calls the SubjectAccessReview API on the configured API server to determine whether each request is authorized

I don't get it about the --kubeconfig flags as my kubelet service is running fine for prometheus.
The api group _authorization.k8s.io/v1beta1_ is enabled as i can see it when i run _kubectl api-version_.

If anyone could enlight me about it as having a monitoring solution working is fine with prometheus but not having acces to my pods logs for debuging for my users is not good.

Anyway have a nice day.

Regards,
Zwordi

**Comment by brancz** [comment]
This is about the apiserver not having permission to ask for pods/logs on the kubelet API, so all you need is give the apiserver serviceaccount/user the appropriate permissions to do so. This should be fixed upstream in kubespray when `--authorization-mode=Webhook` is enabled.

**Comment by Zwordi** [comment]
Hello @brancz ,

Thanks for your reply.
Could you share more practical hints about how could i manage this steps ?
Do i need to update an clusterroles ?

Thanks

**Comment by brancz** [comment]
It slightly depends on your setup, but this is the ClusterRole and ClusterRoleBinding that I have in my cluster:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-apiserver
rules:
- apiGroups:
  - ""
  resources:
  - nodes/proxy
  verbs:
  - get
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-apiserver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-apiserver
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: kube-apiserver
```

**Comment by Zwordi** [comment]
Hello @wgui1 I just try it with success.
I agree with you that it's just an workaround as i found the correct setting in the kubespray ansible repository in order to upgrade my cluster but i still didn't plan this operation yet.

With your solution i'm gonna put this issue as close.
Thanks everyone.
