### ISSUE TITLE
segfault in 0.25.0

### ISSUE THREAD

**Issue by wleese** [coreos/prometheus-operator#2156]
**What did you do?**
Upgraded from 0.23.x to 0.25.0

* Kubernetes version information:

	insert output of `kubectl version` here
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.7-gke.11", GitCommit:"fa90543563c9cfafca69128ce8cd9ecd5941940f", GitTreeState:"clean", BuildDate:"2018-11-08T20:22:21Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	Google's GKE

* Prometheus Operator Logs:

```
prometheus-operator-c866bddc9-fg85p prometheus-operator level=info ts=2018-11-22T10:35:27.809178053Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=monitoring/platform-001
prometheus-operator-c866bddc9-fg85p prometheus-operator panic: runtime error: invalid memory address or nil pointer dereference
prometheus-operator-c866bddc9-fg85p prometheus-operator [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x10549e6]
prometheus-operator-c866bddc9-fg85p prometheus-operator 
prometheus-operator-c866bddc9-fg85p prometheus-operator goroutine 163 [running]:
prometheus-operator-c866bddc9-fg85p prometheus-operator github.com/coreos/prometheus-operator/pkg/prometheus.(*configGenerator).generateServiceMonitorConfig(0xc00043ddc0, 0x2, 0x4, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
prometheus-operator-c866bddc9-fg85p prometheus-operator 	/home/travis/gopath/src/github.com/coreos/prometheus-operator/pkg/prometheus/promcfg.go:385 +0x7d6
prometheus-operator-c866bddc9-fg85p prometheus-operator github.com/coreos/prometheus-operator/pkg/prometheus.(*configGenerator).generateConfig(0xc00043ddc0, 0xc000202a90, 0xc004f72990, 0xc00494ec90, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
prometheus-operator-c866bddc9-fg85p prometheus-operator 	/home/travis/gopath/src/github.com/coreos/prometheus-operator/pkg/prometheus/promcfg.go:166 +0x1dab
prometheus-operator-c866bddc9-fg85p prometheus-operator github.com/coreos/prometheus-operator/pkg/prometheus.(*Operator).createOrUpdateConfigurationSecret(0xc0004a9880, 0xc000202a90, 0xc004f62eb0, 0x1, 0x1, 0x0, 0x0)
prometheus-operator-c866bddc9-fg85p prometheus-operator 	/home/travis/gopath/src/github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:1289 +0x39c
prometheus-operator-c866bddc9-fg85p prometheus-operator github.com/coreos/prometheus-operator/pkg/prometheus.(*Operator).sync(0xc0004a9880, 0xc0145ca0c0, 0x17, 0x1145120, 0xc0002fc170)
prometheus-operator-c866bddc9-fg85p prometheus-operator 	/home/travis/gopath/src/github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:967 +0x143f
prometheus-operator-c866bddc9-fg85p prometheus-operator github.com/coreos/prometheus-operator/pkg/prometheus.(*Operator).processNextWorkItem(0xc0004a9880, 0x0)
prometheus-operator-c866bddc9-fg85p prometheus-operator 	/home/travis/gopath/src/github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:853 +0xfc
prometheus-operator-c866bddc9-fg85p prometheus-operator github.com/coreos/prometheus-operator/pkg/prometheus.(*Operator).worker(0xc0004a9880)
prometheus-operator-c866bddc9-fg85p prometheus-operator 	/home/travis/gopath/src/github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:842 +0x2b
prometheus-operator-c866bddc9-fg85p prometheus-operator created by github.com/coreos/prometheus-operator/pkg/prometheus.(*Operator).Run
prometheus-operator-c866bddc9-fg85p prometheus-operator 	/home/travis/gopath/src/github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:392 +0x23a
```

**Comment by metalmatze** [comment]
Seems like one of your ServiceMonitors has an Endpoint without `Port` nor `TargetPort` and those it panics at this line, if I got this correctly now.
https://github.com/coreos/prometheus-operator/blob/v0.25.0/pkg/prometheus/promcfg.go#L385

Ideas @brancz?

**Comment by wleese** [comment]
Found them. Example:
```
spec:
  endpoints:
  - port: "8080"
  - path: /internal/prometheus
  jobLabel: bol-application
  namespaceSelector:
    matchNames:
    - tamtam
  selector:
    matchLabels:
      bol-application: tamtam
```

**Comment by squat** [comment]
@wleese indeed, you have defined a list of endpoints. The first endpoint specifies `port: “8080”` and the second endpoint specifies only `path: /internal/prometheus`. Looks like we are not handling this correctly. Separately, it seems that maybe you actually intended to specify only ONE endpoint:

```yaml
endpoints:
- port: “8080”
   path: /internal/prometheus
```

**Comment by wleese** [comment]
Yeah, I'm chasing our users to get this fixed on their side and adding validation on our side to prevent this kind of input (we use a provisioning tool to allow users to create their serviceMonitors).
Would be nice not to segfault though ;)

**Comment by jkassis** [comment]
just hit this as well.
