### ISSUE TITLE
k8s python client control operator meet some erro

### ISSUE THREAD

**Issue by gjpei2** [coreos/prometheus-operator#2637]
**What did you do?**
i am using k8s python client to control prometheus-operator,there are some promblem when create prometheusrule.
**Did you expect to see some different?**
can get a successful response 
**Environment**
centos 7.3 ;python2.7
* Prometheus Operator version:
v0.29.0
    `Insert image tag or Git SHA here`
    

* Kubernetes version information:
1.10
    `kubectl version`
    

* Kubernetes cluster kind:
kubeadm
    insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:
when i using python client control my operator ,i write some module like other k8s api , the request path is '/apis/monitoring.coreos.com/v1/namespaces/{namespace}/prometheusrules' ,the method is POST,and I create V1PrometheusRule type like as follows：
swagger_types = {
        'api_version': 'str',
        'kind': 'str',
        'metadata': 'V1ObjectMeta',
        'spec': 'V1PrometheusRuleSpec'
    }

and rule type:
swagger_types = {
        'record': 'str',
        'alert': 'str',
        'expr': 'str',
        'foro': 'str',
        'labels': 'dict(str,str)',
        'annotations': 'dict(str,str)'
    }

but when i run my python script like this:

from kubernetes import client, config
config.kube_config.load_kube_config(config_file="config")
v1 = client.PrometheusRuleV1Api()
#res = v1.list_api_service()
#print res
#res = v1.get_api_resources()
#print res
def creat_prometheusrule_object():
    metadata=client.V1ObjectMeta(labels={"prometheus": "k8s","role":"alert-rules"},name="test",namespace="monitoring")
    #rules=client.V1PrometheusRuleRule(record="up == 1",alert="InstanceDown",expr="up == 1",labels={"severity": "k8s_page"},annotations={"summary":` 'Instance {{ $labels.instance }} down'`})
    summary = "Instance {{ $labels.instance }} down"
    expr = "up{" + "instance!~" +' " ' + '.*8081"' + "}==0"
    print expr
    rules=client.V1PrometheusRuleRule(alert="InstanceDown",expr=expr,labels={"severity": "k8s_page","summary":summary},annotations={"test":"gjpei"})
    spec=client.V1PrometheusRuleSpec(groups=[client.V1PrometheusRuleGroup(name="prometheus-test",rules=[rules])])
    body = client.V1PrometheusRule(
        api_version="monitoring.coreos.com/v1",
        kind="PrometheusRule",
        metadata=metadata,
        spec=spec
        )
    print body
    return body
def create_prometheusrule():
    body = creat_prometheusrule_object()
    res = v1.create_namespaced_prometheus(namespace="monitoring",body=body)
    return res
print create_prometheusrule()

it has erro as follows：

dict(str,str)
Traceback (most recent call last):
  File "get_prometheus_rule.py", line 28, in <module>
    print create_prometheusrule()
  File "get_prometheus_rule.py", line 26, in create_prometheusrule
    res = v1.create_namespaced_prometheus(namespace="monitoring",body=body)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/apis/prometheusrule_v1_api.py", line 60, in create_namespaced_prometheus
    (data) = self.create_namespaced_prometheusrule_with_http_info(namespace, body, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/apis/prometheusrule_v1_api.py", line 151, in create_namespaced_prometheusrule_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/api_client.py", line 339, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/api_client.py", line 179, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/api_client.py", line 254, in deserialize
    return self.__deserialize(data, response_type)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/api_client.py", line 294, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/api_client.py", line 638, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/api_client.py", line 294, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/api_client.py", line 638, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/api_client.py", line 272, in __deserialize
    for sub_data in data]
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/api_client.py", line 294, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/api_client.py", line 638, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/api_client.py", line 272, in __deserialize
    for sub_data in data]
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/api_client.py", line 294, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/api_client.py", line 638, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/api_client.py", line 275, in __deserialize
    sub_kls = re.match('dict\(([^,]*), (.*)\)', klass).group(2)
AttributeError: 'NoneType' object has no attribute 'group'

it show 'NoneType' object has no attribute 'group',but i have dict type ,I want know how to set it correct and i have successful response.in fact ,although it is erro ,the prometheusrule has created successfully in my k8s 

thanks! 
```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by gjpei2** [comment]
i find a space cause this promblem ,dict(str, str) is right,dict(str,str) is wrong.
the reason i don't know
close this issue
