### ISSUE TITLE
generate-manifests.sh fails

### ISSUE THREAD

**Issue by nrobert13** [coreos/prometheus-operator#838]
**What did you do?**
trying to regenerate maniests.
**What did you expect to see?**
a working manifests/grafana/grafana-dashboards.yaml.
**What did you see instead? Under which circumstances?**
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-0
data:
Using base prefix '/usr'
New python executable in /opt/prometheus-operator/contrib/kube-prometheus/.env/bin/python3
Not overwriting existing python script /opt/prometheus-operator/contrib/kube-prometheus/.env/bin/python (you must use /opt/prometheus-operator/contrib/kube-prometheus/.env/bin/python3)
Installing setuptools, pip, wheel...done.
Running virtualenv with interpreter /bin/python3
Collecting git+https://github.com/aknuds1/grafanalib.git@v0.4.0 (from -r requirements.txt (line 1))
  Cloning https://github.com/aknuds1/grafanalib.git (to v0.4.0) to /tmp/pip-g3kr5yp5-build
Requirement already up-to-date: attrs in ./.env/lib/python3.4/site-packages (from grafanalib==0.4.0->-r requirements.txt (line 1))
Installing collected packages: grafanalib
  Found existing installation: grafanalib 0.4.0
    Uninstalling grafanalib-0.4.0:
      Successfully uninstalled grafanalib-0.4.0
  Running setup.py install for grafanalib: started
    Running setup.py install for grafanalib: finished with status 'done'
Successfully installed grafanalib-0.4.0
Traceback (most recent call last):
  File "/opt/prometheus-operator/contrib/kube-prometheus/.env/bin/generate-dashboard", line 11, in <module>
    load_entry_point('grafanalib==0.4.0', 'console_scripts', 'generate-dashboard')()
  File "/opt/prometheus-operator/contrib/kube-prometheus/.env/lib/python3.4/site-packages/grafanalib/_gen.py", line 126, in generate_dashboard_script
    run_script(generate_dashboard)
  File "/opt/prometheus-operator/contrib/kube-prometheus/.env/lib/python3.4/site-packages/grafanalib/_gen.py", line 116, in run_script
    sys.exit(f(sys.argv[1:]))
  File "/opt/prometheus-operator/contrib/kube-prometheus/.env/lib/python3.4/site-packages/grafanalib/_gen.py", line 103, in generate_dashboard
    dashboard = load_dashboard(opts.dashboard)
  File "/opt/prometheus-operator/contrib/kube-prometheus/.env/lib/python3.4/site-packages/grafanalib/_gen.py", line 24, in load_dashboard
    module = SourceFileLoader("dashboard", path).load_module()
  File "<frozen importlib._bootstrap>", line 539, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1614, in load_module
  File "<frozen importlib._bootstrap>", line 596, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/opt/prometheus-operator/contrib/kube-prometheus/assets/grafana/deployment.dashboard.py", line 4, in <module>
    from _grafanalib import *
  File "/opt/prometheus-operator/contrib/kube-prometheus/assets/grafana/_grafanalib.py", line 23
    ], rows=rows, graphTooltip=graphTooltip, **optional_args,
                                                            ^
SyntaxError: invalid syntax
```
there are no dashboard.json files:
```
$ ls -ln assets/grafana/
total 228
drwxrwxr-x 1 1000 1000   296 Dec 21 15:00 __pycache__
-rw-rw-r-- 1 1000 1000  3035 Dec 21 10:19 _grafanalib.py
-rw-rw-r-- 1 1000 1000 16519 Dec 21 10:19 deployment.dashboard.py
-rw-rw-r-- 1 1000 1000 17073 Dec 21 10:19 kubernetes-capacity-planning.dashboard.py
-rw-rw-r-- 1 1000 1000 14013 Dec 21 10:19 kubernetes-cluster-health.dashboard.py
-rw-rw-r-- 1 1000 1000 15937 Dec 21 10:19 kubernetes-cluster-status.dashboard.py
-rw-rw-r-- 1 1000 1000 12138 Dec 21 10:19 kubernetes-control-plane-status.dashboard.py
-rw-rw-r-- 1 1000 1000  7935 Dec 21 10:19 kubernetes-resource-requests.dashboard.py
-rw-rw-r-- 1 1000 1000 15631 Dec 21 10:19 nodes.dashboard.py
-rw-rw-r-- 1 1000 1000  7569 Dec 21 10:19 pods.dashboard.py
-rw-rw-r-- 1 1000 1000   158 Jul  7 12:13 prometheus-datasource.json
-rw-rw-r-- 1 1000 1000 15137 Dec 21 10:19 statefulset.dashboard.py

```
**Environment**

* Kubernetes version information:

$ kubectl version
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:16:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.5+coreos.0", GitCommit:"b8e596026feda7b97f4337b115d1a9a250afa8ac", GitTreeState:"clean", BuildDate:"2017-12-12T11:01:08Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 

	kubespray
* Manifests:
* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by brancz** [comment]
All of those scripts are in a `hack/` folder. We provide no guarantee other than that we make sure that they run successfully with the provided Dockerfile.

I recommend to just do this:

```
cd contrib/kube-prometheus/
make generate
```
